### ISSUE TITLE
Can't build wheel for pyworld

### ISSUE THREAD

**Issue by HighGuard** [hashblen/voice-changer-colab#2]
```
Building wheels for collected packages: pyworld, gin
  error: subprocess-exited-with-error
  
  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Failed building wheel for pyworld
  Building wheel for gin (setup.py) ... done
  Created wheel for gin: filename=gin-0.1.6-py3-none-any.whl size=3363 sha256=4e41861b9b0b9332b484ac7f3f9cd571c5421b316fcea0b4ca4e52172167583a
  Stored in directory: /root/.cache/pip/wheels/d4/87/5b/9aa267e4470bcfab32d6dcc559d7449905894a34b8a89a9abb
Successfully built gin
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/content/voice-changer/server/MMVCServerSIO.py", line 19, in <module>
    from sio.MMVC_SocketIOApp import MMVC_SocketIOApp
  File "/content/voice-changer/server/sio/MMVC_SocketIOApp.py", line 1, in <module>
    import socketio
ModuleNotFoundError: No module named 'socketio'
```

**Comment by hashblen** [comment]
Fixed. There is still the error
```
Building wheels for collected packages: pyworld
  error: subprocess-exited-with-error
  
  × Building wheel for pyworld (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for pyworld (pyproject.toml) ... error
  ERROR: Failed building wheel for pyworld
Failed to build pyworld
ERROR: Could not build wheels for pyworld, which is required to install pyproject.toml-based projects
```
but it works.
